version: "3"
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
  api:
    restart: always
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./mongo.env
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongo-express.env
    depends_on:
      - mongo

volumes:
  mongodb_data:
